version: 2
updates:
  # Keep GitHub Actions up to date (workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    rebase-strategy: auto
    # Don’t let Dependabot edit or mis-parse your digest workflows
    # (it can still bump action versions referenced in them)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Example: Python pip in the root (if/when you want it)
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #     day: "sunday"
  #     time: "09:00"
  #     timezone: "UTC"
  #   open-pull-requests-limit: 5
