# src/team_digest/_footer.py
from __future__ import annotations

try:
    # normal case when installed
    from . import __version__
except Exception:  # fallback in odd import contexts
    __version__ = "unknown"

def append_footer(text: str, fmt: str = "md") -> str:
    """
    Append a small provenance footer to the digest text.

    For Markdown: adds   _Generated by team-digest vX.Y.Z_
    For JSON (or anything else): no-op by default.
    """
    if not isinstance(text, str):
        return text

    if (fmt or "md").lower() == "md":
        footer = f"\n\n_Generated by team-digest v{__version__}_"
        return text + footer

    # non-md formats: keep no-op unless you want to add metadata later
    return text
