name: Daily Digest (schedule)

on:
  schedule:
    - cron: "0 9 * * 1-5"  # 09:00 UTC Mon-Fri
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install tool
        run: |
          python -m pip install --upgrade pip
          pip install team-digest
      - name: Run digest and post to Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          team-digest --format md --input ./logs --from $(date -u -d "yesterday" +%F) --to $(date -u +%F) --post slack
