name: Daily Digest

on:
  schedule:
    # 08:00 local time (set TZ variable in repo settings)
    - cron: "0 8 * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.TZ || 'UTC' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      # Default to packaged examples
      - name: Resolve INPUT_DIR from packaged examples
        run: |
          INPUT_DIR=$(python -c "import pathlib, team_digest; print(pathlib.Path(team_digest.__file__).parent/'examples'/'logs')")
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"

      # Prefer repo INPUT_DIR override, supporting repo-relative or absolute
      - name: Prefer repo INPUT_DIR override (if set)
        if: ${{ vars.INPUT_DIR && vars.INPUT_DIR != '' }}
        run: |
          VAL="${{ vars.INPUT_DIR }}"
          case "$VAL" in
            /*)    echo "INPUT_DIR=$VAL" >> "$GITHUB_ENV" ;;
            *)     echo "INPUT_DIR=${GITHUB_WORKSPACE}/$VAL" >> "$GITHUB_ENV" ;;
          esac

      - name: Generate daily digest
        run: |
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md -o outputs/daily.md
          echo '---- Preview (first 60 lines) ----'
          head -n 60 outputs/daily.md || true

      - name: Post to Slack (if webhook is set)
        if: ${{ secrets.SLACK_WEBHOOK }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          # Post markdown as a code block to preserve formatting
          jq -Rs --arg pre '```' '{text: ($pre + . + $pre)}' < outputs/daily.md \
          | curl -fsSL -H 'Content-Type: application/json' --data-binary @- "$SLACK_WEBHOOK"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: outputs/**
