name: Daily Digest

on:
  schedule:
    - cron: "0 8 * * 1-5"   # Weekdays at 08:00 (see TZ variable)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.DIGEST_TZ || 'UTC' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      - name: Resolve INPUT_DIR (repo logs by default)
        run: |
          set -euo pipefail
          if [ -n "${{ vars.DIGEST_INPUT_DIR }}" ]; then
            INPUT_DIR="${{ vars.DIGEST_INPUT_DIR }}"
          else
            INPUT_DIR="logs"
          fi
          echo "Resolved INPUT_DIR=$INPUT_DIR"
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"

      - name: Generate daily digest
        run: |
          set -euo pipefail
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md -o outputs/daily.md
          # Fix header "(YYYY-MM-DD - YYYY-MM-DD)" → "(YYYY-MM-DD)" if both dates match
          python -c "import re, pathlib; \
p = pathlib.Path('outputs/daily.md'); \
t = p.read_text(encoding='utf-8'); \
m = re.search(r'^(# Team Digest \()(\d{4}-\d{2}-\d{2}) - (\d{4}-\d{2}-\d{2})(\))', t, re.M); \
(p.write_text(t.replace(m.group(0), f'{m.group(1)}{m.group(2)}{m.group(4)}', 1), encoding='utf-8') if m and m.group(2)==m.group(3) else None)"
          echo '---- Preview (first 40 lines) ----'
          head -n 40 outputs/daily.md || true

      - name: Post to Slack (if webhook is set)
        if: ${{ secrets.SLACK_WEBHOOK_URL != '' || secrets.SLACK_WEBHOOK != '' }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL || secrets.SLACK_WEBHOOK }}
        run: |
          set -euo pipefail
          PAYLOAD=$(jq -Rs --arg pre '```' '{text: ($pre + . + $pre)}' < outputs/daily.md)
          curl -fsSL -H 'Content-Type: application/json' --data-raw "$PAYLOAD" "$SLACK_WEBHOOK"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: outputs/**
