name: Daily Digest

on:
  schedule:
    - cron: "0 8 * * 1-5"   # 08:00 local time (see TZ below)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.TZ || 'UTC' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2" jq

      - name: Resolve INPUT_DIR from packaged examples
        run: |
          INPUT_DIR=$(python -c "import pathlib, team_digest; print(pathlib.Path(team_digest.__file__).parent/'examples'/'logs')")
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"

      - name: Compute daily date range (today..today in $TZ)
        run: |
          python - <<'PY' >> "$GITHUB_ENV"
          import os, datetime
          try:
              from zoneinfo import ZoneInfo
          except Exception:
              ZoneInfo = None
          tz = os.environ.get("TZ","UTC")
          today = datetime.datetime.now(ZoneInfo(tz) if ZoneInfo else None).date()
          print(f"RANGE_FROM={today.isoformat()}")
          print(f"RANGE_TO={today.isoformat()}")
          PY

      - name: Generate daily digest
        run: |
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md \
            --from "$RANGE_FROM" --to "$RANGE_TO" \
            -o outputs/daily.md
          echo '---- Preview (first 60 lines) ----'; head -n 60 outputs/daily.md || true

      - name: Post to Slack (if webhook is set)
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          WEBHOOK="${SLACK_WEBHOOK:-${SLACK_WEBHOOK_URL:-}}"
          if [ -n "$WEBHOOK" ]; then
            jq -Rs '{text: ("```" + . + "```")}' < outputs/daily.md \
              | curl -fsSL -H 'Content-Type: application/json' --data-binary @- "$WEBHOOK"
          else
            echo "No Slack webhook secret set; skipping Slack post."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: outputs/**
