name: Daily Digest (schedule)

on:
  # GitHub cron is always evaluated in UTC. Adjust the minutes/hour as needed.
  schedule:
    - cron: "0 14 * * 1-5"  # 14:00 UTC Mon-Fri (example)
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/publish-digests.yml
    with:
      digest: daily
      date: ""              # auto
      dry_run: false
      tz: ${{ vars.DIGEST_TZ || 'UTC' }}
    secrets: inherit
