
name: Daily Digest
on:
  schedule:
    - cron: "0 14 * * *"  # 2pm UTC daily
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip team-digest
      - name: Resolve packaged examples (demo; replace with your logs dir)
        id: logs
        run: |
          python - <<'PY' | tee logs_path.txt
          import importlib.resources as r, team_digest
          print((r.files(team_digest) / "examples" / "logs").__fspath__())
          PY
      - name: Render outputs
        run: |
          mkdir -p out
          team-digest --input "$(cat logs_path.txt)" --format md   --output out/digest.md
          team-digest --input "$(cat logs_path.txt)" --format json --output out/digest.json
      # - name: Post to Slack (optional)
      #   run: team-digest --input "$(cat logs_path.txt)" --format md --post slack
      #   env:
      #     TEAM_DIGEST_SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
