name: Daily Digest (schedule)

on:
  schedule:
    # Weekdays 9:00 America/Chicago (adjust as needed)
    - cron: "0 14 * * 1-5"
  workflow_dispatch: {}

jobs:
  call-publish:
    uses: ./.github/workflows/publish-digests.yml
    with:
      digest: daily
      # leave date blank so the script auto-picks today
      date: ""
      # set to false to actually commit/publish on the schedule
      dry_run: false
