name: Daily Digest
on:
  schedule:
    - cron: "0 13 * * 1-5"   # 8am America/Chicago weekdays (UTC 13:00)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WEBHOOK_1: ${{ secrets.SLACK_WEBHOOK }}
      WEBHOOK_2: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest (from GitHub main)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir "git+https://github.com/anurajdeol90/team-digest@main#egg=team-digest"

      - name: Resolve INPUT_DIR (packaged examples)
        run: |
          INPUT_DIR=$(python -c "import pathlib, team_digest; print(pathlib.Path(team_digest.__file__).parent/'examples'/'logs')")
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"
          echo "Resolved INPUT_DIR=$INPUT_DIR"

      - name: Build digest (file)
        run: |
          set -e
          mkdir -p outputs
          OUT=outputs/daily.md
          team-digest --input "$INPUT_DIR" --format md -o "$OUT"
          echo "---- Preview (first 60 lines) ----"
          head -n 60 "$OUT" || true

      - name: Post to Slack (optional)
        run: |
          WEBHOOK="${WEBHOOK_1:-$WEBHOOK_2}"
          if [ -n "$WEBHOOK" ]; then
            echo "Posting to Slack via webhook…"
            # Escape file contents to JSON and send as {"text": "..."}
            # jq -Rs . reads the file as a single raw string and JSON-escapes it.
            curl -sS -X POST -H 'Content-type: application/json' \
              --data "{\"text\": $(jq -Rs . < outputs/daily.md)}" \
              "$WEBHOOK"
          else
            echo "No Slack webhook provided; skipping Slack."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: outputs/**
