name: Daily Digest

on:
  schedule:
    # 08:00 local time using a configurable timezone (see TZ repo variable)
    - cron: "0 8 * * 1-5"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.TZ || 'UTC' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      - name: Resolve INPUT_DIR from packaged examples
        run: |
          python -c "import os, pathlib, team_digest; \
p = pathlib.Path(team_digest.__file__).parent/'examples'/'logs'; \
open(os.environ['GITHUB_ENV'],'a').write('INPUT_DIR='+str(p)+'\n')"

      - name: Generate & post daily digest
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL || secrets.SLACK_WEBHOOK }}
        run: |
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md -o outputs/daily.md
          echo '---- Preview (first 60 lines) ----'; head -n 60 outputs/daily.md || true

          if [ -n "$SLACK_WEBHOOK" ]; then
            # Post markdown as a Slack code block using jq-safe quoting
            PAYLOAD=$(jq -cn --arg t "$(cat outputs/daily.md)" '{text: "```" + $t + "```"}')
            curl -fsSL -H 'Content-Type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK"
          else
            echo "SLACK_WEBHOOK not set—skipping Slack post."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: outputs/**
