name: Daily Digest

on:
  workflow_dispatch:
    inputs:
      date:
        description: "Date YYYY-MM-DD (optional; default: today UTC)"
        required: false
        type: string
  schedule:
    - cron: "10 0 * * 1-5"  # 00:10 UTC, weekdays

jobs:
  daily:
    runs-on: ubuntu-latest
    env:
      LOGS_DIR: logs
      OUTFILE: outputs/daily.md
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: python -m pip install --upgrade pip

      - name: Resolve date
        id: pick
        shell: bash
        run: |
          if [ -n "${{ inputs.date }}" ]; then
            echo "date=${{ inputs.date }}" >> $GITHUB_OUTPUT
          else
            echo "date=$(date -u +%Y-%m-%d)" >> $GITHUB_OUTPUT
          fi
          echo "Selected date: $(cat $GITHUB_OUTPUT)"

      - name: Aggregate daily → daily.md (group + sort)
        shell: bash
        run: |
          mkdir -p outputs
          python scripts/digest_daily.py \
            --logs-dir "$LOGS_DIR" \
            --date "${{ steps.pick.outputs.date }}" \
            --output "$OUTFILE" \
            --title "Team Digest (${{ steps.pick.outputs.date }})" \
            --group-actions \
            --sort-actions "priority,name,text"
          echo "---- Preview (first 60 lines) ----"
          head -n 60 "$OUTFILE" || true

      - uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: ${{ env.OUTFILE }}

      - name: Post to Slack (optional)
        if: env.SLACK_WEBHOOK_URL != ''
        run: python scripts/post_to_slack.py "$OUTFILE"
