name: Daily Digest

on:
  schedule:
    - cron: "0 8 * * 1-5"   # Weekdays at 08:00 (your TZ below)
  workflow_dispatch:
    inputs:
      input_dir:
        description: "Override INPUT_DIR (repo-relative or absolute)"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.DIGEST_TZ || 'UTC' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      - name: Resolve INPUT_DIR (override → repo var → logs/)
        run: |
          set -euo pipefail
          CANDIDATE="${{ github.event.inputs.input_dir }}"
          if [ -z "$CANDIDATE" ] && [ -n "${{ vars.DIGEST_INPUT_DIR }}" ]; then
            CANDIDATE="${{ vars.DIGEST_INPUT_DIR }}"
          fi
          if [ -z "$CANDIDATE" ]; then
            CANDIDATE="logs"
          fi
          if [ -d "$CANDIDATE" ]; then
            INPUT_DIR="$CANDIDATE"
          elif [ -d "$GITHUB_WORKSPACE/$CANDIDATE" ]; then
            INPUT_DIR="$GITHUB_WORKSPACE/$CANDIDATE"
          else
            INPUT_DIR="$CANDIDATE"
          fi
          echo "Resolved INPUT_DIR=$INPUT_DIR"
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"

      - name: Compute today range
        run: |
          set -euo pipefail
          FROM=$(date -u +%Y-%m-%d)
          TO="$FROM"
          echo "FROM=$FROM  TO=$TO"
          echo "FROM=$FROM" >> "$GITHUB_ENV"
          echo "TO=$TO" >> "$GITHUB_ENV"

      - name: List candidate files (diagnostics)
        run: |
          set -euo pipefail
          echo "All files in $INPUT_DIR:"; ls -la "$INPUT_DIR" || true
          echo
          echo "Files matching notes-YYYY-MM-DD.* in $FROM..$TO:"
          python - <<'PY'
import os, re, datetime as dt, pathlib as p
d = p.Path(os.environ["INPUT_DIR"])
frm = dt.date.fromisoformat(os.environ["FROM"])
to  = dt.date.fromisoformat(os.environ["TO"])
pat = re.compile(r"^notes-(\d{4}-\d{2}-\d{2})\.(md|markdown|txt)$", re.I)
matches = []
if d.is_dir():
  for f in sorted(d.iterdir()):
    m = pat.match(f.name)
    if not m: continue
    day = dt.date.fromisoformat(m.group(1))
    if frm <= day <= to:
      matches.append(f.name)
print("MATCHES:", ", ".join(matches) if matches else "(none)")
PY

      - name: Generate daily digest (single-date header)
        run: |
          set -euo pipefail
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --from "$FROM" --to "$TO" --format md -o outputs/daily.md
          # If the tool printed "(YYYY-MM-DD - YYYY-MM-DD)" with same date, normalize to single date
          python - <<'PY'
import re, io
p = "outputs/daily.md"
t = io.open(p, "r", encoding="utf-8").read()
m = re.search(r'^(# Team Digest \()(\d{4}-\d{2}-\d{2}) - \2(\))', t, re.M)
if m:
    t = t.replace(m.group(0), f"{m.group(1)}{m.group(2)}{m.group(3)}", 1)
    io.open(p, "w", encoding="utf-8").write(t)
PY
          echo '---- Preview (first 40 lines) ----'
          head -n 40 outputs/daily.md || true

      - name: Resolve Slack webhook (optional)
        run: |
          set -euo pipefail
          if [ -n "${{ secrets.SLACK_WEBHOOK_URL }}" ]; then
            echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> "$GITHUB_ENV"
          elif [ -n "${{ secrets.SLACK_WEBHOOK }}" ]; then
            echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK }}" >> "$GITHUB_ENV"
          else
            echo "SLACK_WEBHOOK=" >> "$GITHUB_ENV"
          fi

      - name: Post to Slack (if webhook is set)
        if: env.SLACK_WEBHOOK != ''
        run: |
          set -euo pipefail
          PAYLOAD=$(jq -Rs --arg pre '```' '{text: ($pre + . + $pre)}' < outputs/daily.md)
          curl -fsSL -H 'Content-Type: application/json' --data-raw "$PAYLOAD" "$SLACK_WEBHOOK"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: outputs/**
