name: Daily Digest

on:
  schedule:
    - cron: "0 8 * * 1-5"   # 08:00 local time (see DIGEST_TZ)
  workflow_dispatch:
    inputs:
      INPUT_DIR:
        description: "Override INPUT_DIR (repo-relative or absolute)"
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.DIGEST_TZ || 'UTC' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      - name: Resolve INPUT_DIR (override → repo var → logs/ → examples)
        run: |
          set -e
          CANDIDATE="${{ github.event.inputs.INPUT_DIR }}"
          if [ -z "$CANDIDATE" ] && [ -n "${{ vars.DIGEST_INPUT_DIR }}" ]; then CANDIDATE="${{ vars.DIGEST_INPUT_DIR }}"; fi
          if [ -z "$CANDIDATE" ] && [ -n "${{ vars.DEFAULT_INPUT_DIR }}" ]; then CANDIDATE="${{ vars.DEFAULT_INPUT_DIR }}"; fi
          if [ -z "$CANDIDATE" ]; then CANDIDATE="logs"; fi

          if [ -d "$CANDIDATE" ]; then
            INPUT_DIR="$CANDIDATE"
          elif [ -d "$GITHUB_WORKSPACE/$CANDIDATE" ]; then
            INPUT_DIR="$GITHUB_WORKSPACE/$CANDIDATE"
          else
            INPUT_DIR=""
          fi

          if [ -z "$INPUT_DIR" ]; then
            INPUT_DIR=$(python -c "import pathlib,team_digest; print(pathlib.Path(team_digest.__file__).parent/'examples'/'logs')")
          fi

          echo "Resolved INPUT_DIR=$INPUT_DIR"
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"

      - name: Generate daily digest
        run: |
          set -e
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md -o outputs/daily.md
          echo '---- Preview (first 40 lines) ----'; head -n 40 outputs/daily.md || true

      - name: Post to Slack (if webhook is set)
        env:
          _A: ${{ secrets.SLACK_WEBHOOK_URL }}
          _B: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          set -e
          SLACK_WEBHOOK="${_A:-${_B:-}}"
          if [ -n "$SLACK_WEBHOOK" ]; then
            PAYLOAD=$(jq -Rs --arg pre '```' '{text: ($pre + . + $pre)}' < outputs/daily.md)
            curl -fsSL -H 'Content-Type: application/json' --data-raw "$PAYLOAD" "$SLACK_WEBHOOK"
          else
            echo "SLACK_WEBHOOK not set—skipping Slack post."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest
          path: outputs/**
