name: Daily Digest

on:
  schedule:
    - cron: "0 12 * * *"     # 12:00 UTC daily
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Set DATE (UTC today)
        shell: bash
        run: echo "DATE=$(date -u +%F)" >> "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install team-digest==1.1.18

      - name: Resolve example logs path from installed package
        id: paths
        shell: bash
        run: |
          LOGS=$(python -c "from importlib import resources; print(resources.files('team_digest').joinpath('examples','logs'))")
          echo "LOGS=$LOGS" >> "$GITHUB_ENV"

      - name: Run daily digest
        shell: bash
        run: |
          set -euo pipefail
          team-digest daily \
            --logs-dir "$LOGS" \
            --date "$DATE" \
            --output "daily_${DATE}.md" \
            --group-actions --emit-kpis --owner-breakdown

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: daily-digest-${{ env.DATE }}
          path: daily_${{ env.DATE }}.md
