# .github/dependabot.yml
version: 2
updates: []

updates:
  # Keep GitHub Actions in this repo up to date (checkout, setup-python, etc.)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"          # daily | weekly | monthly
      day: "monday"                # optional: when interval=weekly
      time: "09:00"                # optional: UTC
    open-pull-requests-limit: 4
    rebase-strategy: "auto"        # let Dependabot rebase as needed
    labels:
      - "dependencies"
      - "github-actions"
    # Optional: who should be requested for review
    # reviewers:
    #   - anurajdeol90
    # Optional: automatically assign someone
    # assignees:
    #   - anurajdeol90
