name: Monthly Digest (schedule)

on:
  schedule:
    - cron: "0 8 1 * *"   # 1st of month 08:00 local time
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.TZ || 'UTC' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      - name: Resolve INPUT_DIR from packaged examples
        run: |
          INPUT_DIR=$(python -c "import pathlib, team_digest; print(pathlib.Path(team_digest.__file__).parent/'examples'/'logs')")
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"

      - name: Generate & post monthly digest
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL || secrets.SLACK_WEBHOOK }}
        run: |
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md -o outputs/monthly.md
          echo '---- Preview (first 60 lines) ----'; head -n 60 outputs/monthly.md || true
          if [ -n "$SLACK_WEBHOOK" ]; then
            PAYLOAD=$(jq -cn --arg t "$(cat outputs/monthly.md)" '{text: "```" + $t + "```"}')
            curl -fsSL -H 'Content-Type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK"
          else
            echo "SLACK_WEBHOOK not set—skipping Slack post."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-digest
          path: outputs/**
