name: Monthly Digest (schedule)
on:
  schedule:
    - cron: "0 14 1 * *"     # 9am America/Chicago on the 1st (UTC 14:00)
  workflow_dispatch:
    inputs:
      use_examples:
        description: "Use packaged example logs instead of repo logs/"
        required: false
        default: "true"
        type: choice
        options: ["true", "false"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      - name: Resolve INPUT_DIR (examples or repo logs)
        env:
          USE_EXAMPLES: ${{ inputs.use_examples }}
        run: |
          set -eu
          if [ "${USE_EXAMPLES:-true}" = "true" ]; then
            python - <<'PY'
import os, pathlib, team_digest
p = pathlib.Path(team_digest.__file__).parent/'examples'/'logs'
with open(os.environ["GITHUB_ENV"], "a") as f:
    f.write(f"INPUT_DIR={p}\n")
print(f"Resolved packaged examples to: {p}")
PY
          else
            echo "INPUT_DIR=logs" >> "$GITHUB_ENV"
            echo "Using repo logs/ directory"
          fi

      - name: Monthly digest → Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md --post slack -o outputs/monthly.md
          head -n 60 outputs/monthly.md || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-digest
          path: outputs/**
