name: Monthly Digest (schedule)
on:
  schedule:
    - cron: "0 14 1 * *"     # 9am America/Chicago on the 1st (UTC 14:00)
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=1.1.6,<2"

      - name: Resolve INPUT_DIR (packaged examples)
        run: |
          INPUT_DIR=$(python -c "import pathlib, team_digest; print(pathlib.Path(team_digest.__file__).parent/'examples'/'logs')")
          echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"
          echo "Resolved INPUT_DIR=$INPUT_DIR"

      - name: Monthly digest → Slack
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          mkdir -p outputs
          team-digest --input "$INPUT_DIR" --format md --post slack -o outputs/monthly.md
          echo "---- Preview (first 60 lines) ----"
          head -n 60 outputs/monthly.md || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-digest
          path: outputs/**
