name: Monthly Digest

on:
  schedule:
    - cron: "0 07 1 * *"  # 1st of each month at 07:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Compute previous month date range (UTC)
        shell: bash
        run: |
          FIRST_THIS_MONTH=$(date -u +%Y-%m-01)
          START=$(date -u -d "$FIRST_THIS_MONTH -1 month" +%F)
          END=$(date -u -d "$FIRST_THIS_MONTH -1 day" +%F)
          echo "START=$START" >> "$GITHUB_ENV"
          echo "END=$END"     >> "$GITHUB_ENV"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install team-digest==1.1.18

      - name: Resolve example logs path from installed package
        id: paths
        shell: bash
        run: |
          LOGS=$(python -c "from importlib import resources; print(resources.files('team_digest').joinpath('examples','logs'))")
          echo "LOGS=$LOGS" >> "$GITHUB_ENV"

      - name: Run monthly digest
        shell: bash
        run: |
          set -euo pipefail
          team-digest monthly \
            --logs-dir "$LOGS" \
            --start "$START" \
            --end "$END" \
            --output "monthly_${START}_to_${END}.md" \
            --group-actions --emit-kpis --owner-breakdown

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-digest-${{ env.START }}-to-${{ env.END }}
          path: monthly_${{ env.START }}_to_${{ env.END }}.md
