name: Monthly Digest (schedule)
on:
  schedule:
    - cron: "0 14 1 * *"     # 14:00 UTC on the 1st of each month
  workflow_dispatch: {}

concurrency:
  group: digest-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: ${{ vars.DIGEST_TZ || 'UTC' }}
      DIGEST_INPUT_DIR: ${{ vars.DIGEST_INPUT_DIR }}
      DIGEST_CONFIG: ${{ vars.DIGEST_CONFIG }}
      WEBHOOK_1: ${{ secrets.SLACK_WEBHOOK }}
      WEBHOOK_2: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest (from GitHub main)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir "git+https://github.com/anurajdeol90/team-digest@main#egg=team-digest"

      - name: Resolve source (config or input dir; fallback to packaged examples)
        run: |
          set -e
          if [ -n "$DIGEST_CONFIG" ]; then
            echo "USE_CONFIG=$DIGEST_CONFIG" >> "$GITHUB_ENV"
            echo "Source: CONFIG=$DIGEST_CONFIG"
          elif [ -n "$DIGEST_INPUT_DIR" ]; then
            echo "INPUT_DIR=$DIGEST_INPUT_DIR" >> "$GITHUB_ENV"
            echo "Source: INPUT_DIR=$DIGEST_INPUT_DIR"
          else
            INPUT_DIR=$(python -c "import pathlib, team_digest; print(pathlib.Path(team_digest.__file__).parent/'examples'/'logs')")
            echo "INPUT_DIR=$INPUT_DIR" >> "$GITHUB_ENV"
            echo "Source: INPUT_DIR (examples) -> $INPUT_DIR"
          fi

      - name: Build digest (previous calendar month)
        run: |
          set -e
          mkdir -p outputs
          THIS_MONTH_START=$(date +%Y-%m-01)
          FROM=$(date -d "$THIS_MONTH_START -1 month" +%F)
          TO=$THIS_MONTH_START
          OUT=outputs/monthly.md
          echo "Window: $FROM → $TO (TZ=$TZ)"
          if [ -n "$USE_CONFIG" ]; then
            team-digest --config "$USE_CONFIG" --format md --from "$FROM" --to "$TO" -o "$OUT"
          else
            team-digest --input "$INPUT_DIR" --format md --from "$FROM" --to "$TO" -o "$OUT"
          fi
          echo "---- Preview (first 60 lines) ----"
          head -n 60 "$OUT" || true

      - name: Post to Slack (optional)
        run: |
          WEBHOOK="${WEBHOOK_1:-$WEBHOOK_2}"
          if [ -n "$WEBHOOK" ]; then
            OUT=outputs/monthly.md
            payload=$(python - "$OUT" <<'PY'
import json, sys
p = sys.argv[1]
with open(p, encoding="utf-8") as f:
    text = f.read()
print(json.dumps({"text": f"```\n{text}\n```"}))
PY
)
            curl -sS -X POST -H 'Content-type: application/json' --data "$payload" "$WEBHOOK"
          else
            echo "No Slack webhook provided; skipping Slack."
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monthly-digest
          path: outputs/**
