name: Monthly Digest (schedule)

on:
  schedule:
    # 1st of the month 9:00 America/Chicago
    - cron: "0 14 1 * *"
  workflow_dispatch: {}

jobs:
  call-publish:
    uses: ./.github/workflows/publish-digests.yml
    with:
      digest: monthly
      date: ""
      dry_run: false
