name: Monthly Digest (schedule)

on:
  schedule:
    - cron: "0 16 1 * *"   # 16:00 UTC on the 1st of the month (example)
  workflow_dispatch:

jobs:
  run:
    uses: ./.github/workflows/publish-digests.yml
    with:
      digest: monthly
      date: ""              # auto
      dry_run: false
      tz: ${{ vars.DIGEST_TZ || 'UTC' }}
    secrets: inherit
