name: Monthly Digest (1st @ 9am CT)

on:
  workflow_dispatch:
  schedule:
    # 9am CDT (UTC-5) → 14:00 UTC on day 1
    - cron: "0 14 1 * *"
    # 9am CST (UTC-6) → 15:00 UTC on day 1
    - cron: "0 15 1 * *"

permissions:
  contents: write

concurrency:
  group: monthly-digest
  cancel-in-progress: true

jobs:
  monthly:
    runs-on: ubuntu-latest
    env:
      INPUT_DIR: ${{ vars.DIGEST_INPUT_DIR }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      DIGEST_EMAIL_FROM: ${{ secrets.DIGEST_EMAIL_FROM }}
      DIGEST_EMAIL_TO: ${{ secrets.DIGEST_EMAIL_TO }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install team-digest
        run: |
          python -m pip install --upgrade pip
          pip install "team-digest>=0.1.10,<0.2"

      - name: Compute previous calendar month window (America/Chicago)
        id: window
        run: |
          START_DATE=$(TZ=America/Chicago date -d "$(TZ=America/Chicago date +%Y-%m-01) -1 month" +%F' 00:00:00')
          END_DATE=$(TZ=America/Chicago date -d "$(TZ=America/Chicago date +%Y-%m-01) -1 second" +%F' %T')
          LABEL=$(TZ=America/Chicago date -d "$(TZ=America/Chicago date +%Y-%m-01) -1 month" +%Y-%m)
          echo "start=$START_DATE" >> $GITHUB_OUTPUT
          echo "end=$END_DATE" >> $GITHUB_OUTPUT
          echo "label=$LABEL" >> $GITHUB_OUTPUT

      - name: Ensure input dir exists
        run: |
          IN="${INPUT_DIR:-logs}"
          mkdir -p "$IN"

      - name: Collect inputs into temp_input/
        run: |
          set -e
          IN="${INPUT_DIR:-logs}"
          mkdir -p temp_input
          if [ -d "$IN" ]; then
            find "$IN" -type f -newermt "${{ steps.window.outputs.start }}" ! -newermt "${{ steps.window.outputs.end }}" -print0 \
              | xargs -0 -I{} cp "{}" "temp_input/$(basename "{}")" || true
          fi
          echo "Collected $(ls -1 temp_input 2>/dev/null | wc -l) files"

      - name: Generate digest markdown
        run: |
          mkdir -p outputs
          OUT="outputs/monthly_${{ steps.window.outputs.label }}.md"
          SRC="temp_input"
          [ -z "$(ls -A temp_input 2>/dev/null)" ] && SRC="${INPUT_DIR:-logs}"
          team-digest --input "$SRC" --format md > "$OUT"
          echo "OUTFILE=$OUT" >> $GITHUB_ENV

      - name: Update local main (rebase)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main

      - name: Commit digest to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(digest): add ${{ env.OUTFILE }}"
          file_pattern: outputs/*.md
          # push_options: '--force-with-lease'   # optional safety net

      - name: Post to Slack (optional)
        if: ${{ env.SLACK_WEBHOOK_URL != '' }}
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":spiral_calendar_pad: Monthly digest for ${{ steps.window.outputs.label }} is ready.\n${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/${{ env.OUTFILE }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Email digest (optional)
        if: "${{ env.SMTP_SERVER != '' && env.DIGEST_EMAIL_TO != '' }}"
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Monthly Team Digest (${{ steps.window.outputs.label }})"
          from: ${{ secrets.DIGEST_EMAIL_FROM }}
          to: ${{ secrets.DIGEST_EMAIL_TO }}
          secure: true
          convert_markdown: true
          body: |
            Monthly digest is attached and committed to the repo.
            ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/${{ env.OUTFILE }}
          attachments: ${{ env.OUTFILE }}

      - name: Notify failure to Slack (optional)
        if: failure() && env.SLACK_WEBHOOK_URL != ''
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": ":warning: *Monthly Digest* failed on `${{ github.ref }}`.\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
