name: Release (PyPI via Trusted Publishing)

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip build
          rm -rf dist build *.egg-info || true
          python -m build
          ls -la dist
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   # REQUIRED for OIDC
      contents: read
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: dist
      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
