name: Release

on:
  push:
    branches:
      - main
    paths:
      - "src/team_digest/__init__.py"  # trigger only if version file changes
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install -U pip
          pip install build twine

      - name: Build dist (sdist + wheel)
        run: python -m build

      - name: Twine check
        run: python -m twine check dist/*

      - name: Sanity: examples packaged in wheel
        run: |
          python - <<'PY'
          import glob, zipfile, sys
          wh = sorted(glob.glob("dist/*.whl"))[0]
          print("Inspecting", wh)
          with zipfile.ZipFile(wh) as z:
              files = [n for n in z.namelist() if n.startswith("team_digest/examples/")]
              print("\n".join(files) or "NO_EXAMPLES_FOUND")
              if not files:
                  sys.exit("ERROR: examples/ missing from wheel")
          PY

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
